[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Optional: Set NPM_FLAGS directly in netlify.toml
# Uncomment the line below if you want to set it here instead of in Netlify UI
NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-react-start"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
