/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as BrandIndexRouteImport } from './routes/brand/index'
import { Route as CustomersCaseStudyRouteImport } from './routes/customers/$caseStudy'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/brand/',
  path: '/brand/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCaseStudyRoute = CustomersCaseStudyRouteImport.update({
  id: '/customers/$caseStudy',
  path: '/customers/$caseStudy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/customers/$caseStudy': typeof CustomersCaseStudyRoute
  '/brand': typeof BrandIndexRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/customers/$caseStudy': typeof CustomersCaseStudyRoute
  '/brand': typeof BrandIndexRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/customers/$caseStudy': typeof CustomersCaseStudyRoute
  '/brand/': typeof BrandIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/customers/$caseStudy'
    | '/brand'
    | '/customers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pricing' | '/customers/$caseStudy' | '/brand' | '/customers'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/customers/$caseStudy'
    | '/brand/'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  CustomersCaseStudyRoute: typeof CustomersCaseStudyRoute
  BrandIndexRoute: typeof BrandIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/': {
      id: '/brand/'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$caseStudy': {
      id: '/customers/$caseStudy'
      path: '/customers/$caseStudy'
      fullPath: '/customers/$caseStudy'
      preLoaderRoute: typeof CustomersCaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  CustomersCaseStudyRoute: CustomersCaseStudyRoute,
  BrandIndexRoute: BrandIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
